# app/models/device_registry.py
from __future__ import annotations

from datetime import datetime
from typing import Optional
from uuid import UUID as UUID_Type

from sqlalchemy import BigInteger, DateTime, Index, String, Text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from .base import Base
# from .telemetry_latest import TelemetryLatest


class DeviceRegistry(Base):
    """
    Registry of devices that are allowed to send telemetry.
    """

    __tablename__ = "device_registry"
    __table_args__ = (
        Index("ix_device_registry_device_uuid", "device_uuid", unique=True),
        {"schema": "db_schema"},
    )

    id: Mapped[int] = mapped_column(
        BigInteger,
        primary_key=True,
        doc="Surrogate key generated by the database.",
    )

    alias: Mapped[Optional[str]] = mapped_column(
        String(64),
        # nullable=False,
        doc="debug alias for the device.",
    )

    device_uuid: Mapped[UUID_Type] = mapped_column(
        PG_UUID(as_uuid=True),
        nullable=False,
        unique=True,
        doc="Public-facing UUID used by the device and for authentication.",
    )

    api_key_hash: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc="Hashed API key. Plaintext API keys are never stored.",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        doc="Timestamp when the device was added to the telemetry registry (UTC).",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        # DB trigger db_schema.set_updated_at() is responsible for keeping this fresh.
        doc="Timestamp when this registry row was last updated (UTC).",
    )

    # # One-to-one relationship to TelemetryLatest.
    # latest_telemetry: Mapped[Optional["TelemetryLatest"]] = relationship(
    #     "TelemetryLatest",
    #     back_populates="device",
    #     uselist=False,
    #     lazy="joined",
    #     doc="Latest telemetry snapshot for this device, if any.",
    # )

    def __repr__(self) -> str:
        return (
            f"<DeviceRegistry id={self.id} "
            f"alias={self.alias!r} uuid={self.device_uuid}>"
        )
