# app/models/telemetry_event.py
from __future__ import annotations

from datetime import datetime
from uuid import UUID as UUID_Type

from sqlalchemy import BigInteger, DateTime, Float
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from .base import Base


class TelemetryEvent(Base):
    """
    Historical telemetry events emitted by devices.
    """

    __tablename__ = "telemetry_event"
    __table_args__ = {"schema": "db_schema"}

    id: Mapped[int] = mapped_column(
        BigInteger,
        primary_key=True,
        doc="Surrogate key generated by the database.",
    )

    device_uuid: Mapped[UUID_Type] = mapped_column(
        PG_UUID(as_uuid=True),
        nullable=False,
        doc="UUID of the device emitting this telemetry event.",
    )

    x_coord: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        doc="X coordinate.",
    )

    y_coord: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        doc="Y coordinate.",
    )

    device_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        doc="Timestamp reported by the device itself.",
    )

    system_time_utc: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        doc="Server-side UTC timestamp when telemetry was ingested.",
    )

    def __repr__(self) -> str:
        return (
            f"<TelemetryEvent id={self.id} device_uuid={self.device_uuid} "
            f"device_time={self.device_time} system_time_utc={self.system_time_utc} "
            f"x={self.x_coord} y={self.y_coord}>"
        )
