# app/models/telemetry.py
from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Column,
    DateTime,
    Float,
    ForeignKey,
    PrimaryKeyConstraint,
)
from sqlalchemy.orm import relationship

from .base import Base


class Telemetry(Base):
    """
    ORM mapping for db_schema.telemetry.

    Matches DDL:

        CREATE TABLE db_schema.telemetry (
            id          BIGSERIAL       NOT NULL,
            device_id   BIGINT          NOT NULL REFERENCES db_schema.device(id) ON DELETE CASCADE,
            x_coord     DOUBLE PRECISION NOT NULL,
            y_coord     DOUBLE PRECISION NOT NULL,
            recorded_at TIMESTAMPTZ     NOT NULL,
            device_time TIMESTAMPTZ,
            PRIMARY KEY (id, recorded_at)
        )
        PARTITION BY RANGE (recorded_at);
    """

    __tablename__ = "telemetry"
    __table_args__ = (
        PrimaryKeyConstraint("id", "recorded_at", name="pk_telemetry"),
        {"schema": "db_schema"},
    )

    id = Column(
        BigInteger,
        nullable=False,          
        doc="Surrogate key generated by the database (BIGSERIAL).",
    )

    recorded_at = Column(
        DateTime(timezone=True),
        nullable=False,         
        doc="Server-side timestamp when telemetry was recorded (partition key).",
    )

    device_id = Column(
        BigInteger,
        ForeignKey("db_schema.device.id", ondelete="CASCADE"),
        nullable=False,
        doc="Foreign key referencing db_schema.device(id).",
    )

    x_coord = Column(
        Float,
        nullable=False,
        doc="X coordinate (DOUBLE PRECISION).",
    )

    y_coord = Column(
        Float,
        nullable=False,
        doc="Y coordinate (DOUBLE PRECISION).",
    )

    device_time = Column(
        DateTime(timezone=True),
        nullable=True,
        doc="Timestamp reported by the device itself (may differ from recorded_at).",
    )

    device = relationship(
        "Device",
        back_populates="telemetry_points",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        return (
            f"<Telemetry id={self.id} device_id={self.device_id} "
            f"recorded_at={self.recorded_at} x={self.x_coord} y={self.y_coord}>"
        )
