\echo '\n######## Creating tables... ########\n'

\c app_db;

SET ROLE app_user;
-- ==============================
-- Table: device
-- ==============================
CREATE TABLE IF NOT EXISTS db_schema.device (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)    NOT NULL,
    type        VARCHAR(100)    NOT NULL,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    
    CONSTRAINT uq_device_name UNIQUE (name)
);

-- Composite index to speed up queries filtering by type and name
CREATE INDEX IF NOT EXISTS idx_device_type_name
    ON db_schema.device (type, name);

-- Generic function for updated_at
CREATE OR REPLACE FUNCTION db_schema.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- trigger to call updated_at function
DROP TRIGGER IF EXISTS trg_device_set_updated_at ON db_schema.device;
CREATE TRIGGER trg_device_set_updated_at
BEFORE UPDATE ON db_schema.device
FOR EACH ROW
EXECUTE FUNCTION db_schema.set_updated_at();


-- ==============================
-- Table: device_position
-- ==============================
CREATE TABLE IF NOT EXISTS db_schema.device_position (
    device_id       BIGINT              NOT NULL,
    ts              TIMESTAMPTZ         NOT NULL DEFAULT now(),
    x               DOUBLE PRECISION    NOT NULL,
    y               DOUBLE PRECISION    NOT NULL,

    CONSTRAINT pk_device_position PRIMARY KEY (device_id, ts),

    CONSTRAINT chk_xy_range
        CHECK (x >= 0 AND x <= 10 AND y >= 0 AND y <= 10),

    CONSTRAINT fk_device_position_device
        FOREIGN KEY (device_id)
        REFERENCES db_schema.device (id)
        ON DELETE CASCADE
);

-- index: time query
CREATE INDEX IF NOT EXISTS idx_device_position_ts
    ON db_schema.device_position (ts DESC);

RESET ROLE;

-- Confirm
SELECT 
    schemaname,
    tablename,
    tablespace
FROM pg_tables 
WHERE schemaname = 'db_schema'
ORDER BY tablename;


