-- 04_tb_device_registry.sql
\echo
\echo '######## Creating table: device_registry ########'
\echo

\connect app_db
SET ROLE app_owner;

-- ===========================
-- Table: db_schema.device_registry – devices that enable tracking.
-- ===========================
CREATE TABLE IF NOT EXISTS db_schema.device_registry (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias           VARCHAR(64),        -- for debug
    device_uuid     UUID            NOT NULL UNIQUE,
    api_key_hash    TEXT            NOT NULL,           
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Trigger: maintain updated_at on change
-- DROP TRIGGER IF EXISTS trg_device_registry_set_updated_at ON db_schema.device;
CREATE TRIGGER trg_device_registry_set_updated_at
BEFORE UPDATE ON db_schema.device_registry
FOR EACH ROW
EXECUTE FUNCTION db_schema.set_updated_at();
