-- 05_tb_telemetry_event.sql
\echo
\echo '######## Creating table: telemetry_event ########'
\echo

\connect app_db
SET ROLE app_owner;

-- ===========================
-- Table: telemetry_event
-- Full historical log of all accepted telemetry events
-- ===========================
CREATE TABLE IF NOT EXISTS db_schema.telemetry_event (
    id                BIGINT                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_uuid       UUID                    NOT NULL,
    x_coord           DOUBLE PRECISION        NOT NULL,
    y_coord           DOUBLE PRECISION        NOT NULL,
    device_time       TIMESTAMPTZ             NOT NULL,
    system_time_utc   TIMESTAMPTZ             NOT NULL DEFAULT now()
);

-- Index: last location query
CREATE INDEX IF NOT EXISTS idx_telemetry_event_device_system_time_utc
    ON db_schema.telemetry_event (device_uuid, system_time_utc DESC);

-- confirm
SELECT
    table_schema,
    table_name,
    table_type
FROM information_schema.tables
WHERE table_schema = 'db_schema'
  AND table_name   = 'telemetry_event';


SELECT
    schemaname,
    tablename,
    indexname,
    indexdef
FROM pg_indexes
WHERE schemaname = 'db_schema'
  AND tablename  = 'telemetry_event'
ORDER BY indexname;
