\c app_db;

-- init.sql
CREATE USER app_user WITH PASSWORD 'postgres';
CREATE SCHEMA db_schema AUTHORIZATION app_user;
GRANT ALL PRIVILEGES ON SCHEMA db_schema TO app_user;

SET ROLE app_user;

CREATE TABLE IF NOT EXISTS db_schema.trip (
    trip_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMPTZ DEFAULT now(),
    start_station VARCHAR(255) NOT NULL
);

INSERT INTO db_schema.trip (start_station) VALUES ('Central station'), ('Arial station');
RESET ROLE;

-- Confirm
SELECT 
    schemaname,
    tablename,
    tablespace
FROM pg_tables 
WHERE schemaname = 'db_schema'
ORDER BY tablename;

SELECT *
FROM db_schema.trip;